###########################################################
### Welcome to China Cafe!
### This config file customizes your restaurant's website. Explore settings to represent your brand and offerings.
###########################################################

############################
# --- Required options --- #
############################

# Name of website
title: China Cafe

# Your name to show in the footer
author: Justin Crowder

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Home: "/"
  Menu: "menu"
  About Us: "about-us"
  Contact: "contact"

################
# --- Logo --- #
################

# Logo for the navigation bar - ideally the restaurant's logo
avatar: "/assets/img/china-cafe-logo.png"

# Circular logo setting
round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "contact@chinacafe.com"
  facebook: ChinaCafe
  instagram: ChinaCafe
  yelp: China-Cafe
  telephone: "+11234567890"

###########################
# --- General options --- #
###########################

# Social network share links to show in posts/pages
share-links-active:
  twitter: true
  facebook: true
  instagram: true

# Display link to the website in the footer
url-pretty: "ChinaCafe.com"

# Add website title to all page titles
title-on-all-pages: true

# Customize the look with your colors
navbar-col: "#A52A2A"
navbar-text-col: "#FFFFFF"
page-col: "#FFFFFF"
text-col: "#000000"
link-col: "#A52A2A"
hover-col: "#800000"
footer-col: "#A52A2A"
footer-text-col: "#FFFFFF"
footer-link-col: "#FFFFFF"
footer-hover-col: "#800000"

#################################
# --- Web Analytics Section --- #
#################################

# Google Analytics or other web analytics tool IDs can be added here for tracking

####################
# --- Comments --- #
####################

# If you wish to enable comments on blog posts or pages, configure Disqus or another supported comments system

################
# --- Misc --- #
################

# Date format for blog posts or events
date_format: "%B %-d, %Y"

#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

# Technical settings for Jekyll and plugins
timezone: "America/New_York"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
